version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:024129697769:task-definition/samplepyapp:2"
        LoadBalancerInfo:
          ContainerName: "sampleapp"
          ContainerPort: "80"
        PlatformVersion: "LATEST"
